#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := espruino-esp32

# attempted to set only components to build - could not get clean build
#COMPONENTS :=  app_update  bootloader_support  coap  driver  esptool_py  expat  freertos  json  lwip     micro-ecc  nghttp     openssl          sdmmc      tcpip_adapter  vfs     \
#        xtensa-debug-module bootloader         bt         cxx   esp32   ethernet    fatfs  idf_test  log   mbedtls  newlib     nvs_flash  partition_table  spi_flash  ulp            wpa_supplicant

# Components not used
#  

include $(IDF_PATH)/make/project.mk

